In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [3]:
a = np.ones(20)
a = a * 2**np.arange(1,21)/np.arange(1,21)
print(a)

[2.00000000e+00 2.00000000e+00 2.66666667e+00 4.00000000e+00
 6.40000000e+00 1.06666667e+01 1.82857143e+01 3.20000000e+01
 5.68888889e+01 1.02400000e+02 1.86181818e+02 3.41333333e+02
 6.30153846e+02 1.17028571e+03 2.18453333e+03 4.09600000e+03
 7.71011765e+03 1.45635556e+04 2.75941053e+04 5.24288000e+04]


**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
a = np.ones(6)
a = a * 0.1**(3*np.arange(6)) * 0.2**(4*np.arange(6))
print(sum(a))

1.00000160000256


**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [5]:
a = np.zeros((8, 8))
a[::2, ::2]= 1
a[1::2, 1::2]= 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [6]:
X = np.random.random((5, 2))
r = (X[:,0]**2 + X[:,1]**2)**0.5
phi = np.arctan(X[:,1]/X[:,0])
print(r, phi)

[0.84463519 1.28114701 0.80005583 1.07502654 0.29949184] [0.40476931 0.75444018 0.48018649 0.57121478 0.72197297]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [7]:
X = np.random.random((10, 10))
ind = np.unravel_index(np.argmax(X), X.shape)
print(ind)

(4, 9)


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [8]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
D = (X[:, 0]-y[0][0])**2 + (X[:, 1]-y[0][1])**2
ind = np.unravel_index(np.argmin(D), D.shape)
print(X[ind])

[0.21220583 0.84159229]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [9]:
@np.vectorize
def foo(x):
    if x < 0:
        return x*x + 2*x + 6
    if x <= 2:
        return x + 6
    return x*x + 4*x - 4

X = np.arange(-3, 4)
print(foo(X))

[ 9  6  5  6  7  8 17]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [10]:
X = np.random.random((10, 10))
M = np.ones((1,10)) * np.mean(X, axis=1)
Y = X - M.T
print(np.mean(Y, axis=1))

[-5.55111512e-17 -3.33066907e-17  1.11022302e-17 -7.77156117e-17
  3.33066907e-17  2.22044605e-17 -5.55111512e-17 -1.11022302e-17
  8.88178420e-17  3.88578059e-17]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [11]:
X = np.random.normal(loc=5, scale=2., size=1000)
M = np.mean(X)
D = np.mean(X**2) - M*M
print(M, " ", D)

5.02394521335959   4.227685716257984


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [12]:
A = np.zeros((5,5))
A[0] = np.arange(5)
A[1] =  np.roll(A[0], -1, axis = 0)
A[2] =  np.roll(A[0], -2, axis = 0)
A[3] =  np.roll(A[0], +2, axis = 0)
A[4] =  np.roll(A[0], +1, axis = 0)
print(A)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 0.]
 [2. 3. 4. 0. 1.]
 [3. 4. 0. 1. 2.]
 [4. 0. 1. 2. 3.]]


**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [16]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 4, 0, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [17]:
def sample_1(x, c):
    assert len(x) > 0
    s = np.sum(x)
    res = np.repeat(np.cumsum(x),c).reshape((len(x), c)).astype("float32")
    val = s * np.random.random(c)
    res -= val
    res[res>=0]=1
    return  np.argmax(res, axis = 0)
            
sample_1([50, 3, 1, 7, 20], 5)

array([4, 3, 1, 0, 3], dtype=int64)